defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-400epochs-bs-1024-r50-stl10"
method: "simclr"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  temperature: 0.2
data:
  dataset: stl10
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 1024
  lr: 0.8
  classifier_lr: 0.2
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
