name: base
channels:
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.5.0
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - conda=24.11.2
  - conda-anaconda-telemetry=0.1.1
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.11.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=43.0.3
  - distro=1.9.0
  - expat=2.6.4
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.11.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - menuinst=2.2.0
  - ncurses=6.4
  - nlohmann_json=3.11.2
  - openssl=3.0.15
  - packaging=24.2
  - pcre2=10.42
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.8
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.1.0
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.5
  - truststore=0.8.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - attrs==24.3.0
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - filelock==3.16.1
      - fire==0.7.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.68.1
      - h5py==3.12.1
      - huggingface-hub==0.27.0
      - hydra-core==1.3.2
      - imageio==2.36.1
      - importlib-resources==6.4.5
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonargparse==4.35.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning==2.1.2
      - lightning-bolts==0.7.0
      - lightning-flash==0.8.2
      - lightning-utilities==0.11.9
      - llvmlite==0.44.0
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - medmnist==3.0.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-dali-cuda110==1.46.0
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvimgcodec-cu11==0.4.1.21
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvjpeg2k-cu11==0.8.1.40
      - nvidia-nvtiff-cu11==0.4.0.62
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - pandas==2.2.3
      - pillow==11.0.0
      - pip==23.1
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.1
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydeprecate==0.3.2
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.5
      - pytz==2024.2
      - pyyaml==6.0.2
      - safetensors==0.4.5
      - scikit-image==0.25.0
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - six==1.16.0
      - smmap==5.0.1
      - solo-learn==1.0.6
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - timm==1.0.12
      - torch==2.5.1
      - torchmetrics==0.10.3
      - torchvision==0.20.1
      - triton==3.1.0
      - typeshed-client==2.7.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - umap-learn==0.5.7
      - wandb==0.19.1
      - werkzeug==3.1.3
      - yarl==1.18.3
