defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-vit-in100"
method: "robyol"
backbone:
  name: "vit_small"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  au_scale_loss: 0.0
momentum:
  base_tau: 0.99
  final_tau: 1
data:
  dataset: imagenet100
  train_path: "/home/ids/rareme/imagenet-100/train"
  val_path: "/home/ids/rareme/imagenet-100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 6.0e-4
  classifier_lr: 6.0e-4
  weight_decay: 0.1
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0, 1] #SBATCH --gres=gpu:2
sync_batchnorm: True #SBATCH --gpus-per-node=2
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
