defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private_jeanzay.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-imagenet"
method: "byol"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: imagenet
  train_path: "/lustre/fswork/dataset/imagenet/train" # "/projects/common/imagenet/ILSVRC/Data/CLS-LOC/train"
  val_path: "/lustre/fswork/dataset/imagenet/val" # "/projects/common/imagenet/ILSVRC/Data/CLS-LOC/test"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 512
  lr: 0.1
  classifier_lr: 0.05
  weight_decay: 1e-6
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: False
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
# accumulate_grad_batches: 16
